name: xsysinfo software CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: stefanreinauer/amiga-gcc:gcc-v13.3

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Mark git directory as safe
      run: git config --global --add safe.directory '*'

    - name: Building all targets
      run: make all

    - name: Archive CI artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Xsysinfo Program
          path: ${{ github.workspace }}/xSysInfo

    - name: Find ADF filename
      id: adf
      run: echo "filename=$(ls xsysinfo-*.adf)" >> $GITHUB_OUTPUT

    - name: Find LHA filename
      id: lha
      run: echo "filename=$(ls xsysinfo-*.lha)" >> $GITHUB_OUTPUT

    - name: Archive CI artifacts (ADF)
      uses: actions/upload-artifact@v4
      with:
          name: ${{ steps.adf.outputs.filename }}
          path: ${{ github.workspace }}/${{ steps.adf.outputs.filename }}

    - name: Archive CI artifacts (LHA)
      uses: actions/upload-artifact@v4
      with:
          name: ${{ steps.lha.outputs.filename }}
          path: ${{ github.workspace }}/${{ steps.lha.outputs.filename }}
