name: A4091 Draft Release

on:
  push:
    tags:
      - "release_*"
  workflow_dispatch:

permissions:
  contents: write  # needed for creating GitHub releases

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-latest
    container: stefanreinauer/amiga-gcc:gcc-v13.3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Mark git directory as safe
        run: git config --global --add safe.directory '*'

      - name: Build all artifacts
        run: make all

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            xSysInfo
            xsysinfo-*.adf
            xsysinfo-*.lha
          if-no-files-found: error

  release:
    name: Create GitHub Draft Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout (required by gh-release)
        uses: actions/checkout@v4

      - name: Mark git directory as safe
        run: git config --global --add safe.directory '*'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: artifacts

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/xSysInfo
            artifacts/xsysinfo-*.adf
            artifacts/xsysinfo-*.lha
